spring:
  application:
    name: onlinepharmacy-news
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/news?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: qwerty
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

server:
  port: 8081

news.retention.period: P30D
jwt:
  secret: ${JWT_KEY:WSdv1kEE1tCT1a8ihRSqfwMNzlPBq8IWSdv1kEE1tCT1a8ihRSqfwMNzlPBq8IWSdv1kEE1tCT1a8ihRSqfwMNzlPBq8I}